markdown: redcarpet
permalink: /:categories/:title.html
url:
lsi: false
pygments: true
safe: true
auto: false

paginate: 8
paginate_path: "page:num"

# presonal config
title: Zhiyuan MA's Blog
description: Zhiyuan MA's Blog, powered by Jekyll...
feed:

author: Steven Pan

seo:
  keyword:
  description:
config:
  js_dir:
  img_dir:
  css_dir:
